#!/bin/csh -f

pdfjam -o lecture-1.pdf lectures.pdf 6-13
pdfjam -o lecture-2.pdf lectures.pdf 14-24
pdfjam -o lecture-3.pdf lectures.pdf 25-31
pdfjam -o lecture-4.pdf lectures.pdf 32-37
pdfjam -o lecture-5.pdf lectures.pdf 38-44
pdfjam -o lecture-6.pdf lectures.pdf 45-50
pdfjam -o lecture-7.pdf lectures.pdf 51-58
pdfjam -o lecture-8.pdf lectures.pdf 59-64
pdfjam -o lecture-9.pdf lectures.pdf 65-73
pdfjam -o lecture-10.pdf lectures.pdf 74-78
pdfjam -o lecture-11.pdf lectures.pdf 79-83
pdfjam -o lecture-12.pdf lectures.pdf 84-88
pdfjam -o lecture-13.pdf lectures.pdf 89-
